### ISSUE TITLE
Sweetify not showing alert message

### ISSUE THREAD

**Issue by bruce619** [Atrox/sweetify-django#11]
I tried using the sweetify exactly how it was explained but I don't get any alert.

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            sweetify.success(self.request, 'Successfully applied for this job!')
            return self.form_valid(form)
        else:
            sweetify.error(self.request, 'Your application was unsuccessful. Kindly re-apply with correct details')
            return HttpResponseRedirect(reverse_lazy('job-detail', kwargs={'id': self.kwargs['job_id']}))

**Comment by Atrox** [comment]
Hey @bruce619, did you follow all the installation instructions and did you install [sweetalert](https://github.com/sweetalert2/sweetalert2)?

**Comment by bruce619** [comment]
Yes I did. I pip installed it.
Added it to my installed app in my settings.py
specified the library in my settings.py
Loaded it in my base.html
And imported it in my views.py

It didn't show any alert

**Comment by Atrox** [comment]
On your site, run this in the console:
```js
Swal.fire('Good job!', 'You clicked the button!', 'success')
```

Does it show the sweetalert dialog?

**Comment by bruce619** [comment]
On the console it shows an error Swal not defineed

**Comment by Atrox** [comment]
You have to install sweetalert2, the library, itself.
See here: https://sweetalert2.github.io/#download

**Comment by bruce619** [comment]
Okay I get the alert now, but sweetify.success, sweetify.info,
sweetify.danger and sweetify.primary all bring out the same styling. Is
there something I'm not doing right

**Comment by Atrox** [comment]
Sorry but without an example I can't really tell where the problem lies. Does the alert have the correct css classes?

**Comment by bruce619** [comment]
I was able to get it to work.  Thanks for your help

**Comment by Atrox** [comment]
Awesome, great to hear :). Feel free to open another issue if you encounter any other problems while using the package.

**Comment by balarameswar** [comment]
> You have to install sweetalert2, the library, itself.
> See here: https://sweetalert2.github.io/#download

how to install swwetalert in django . I am using vs code I did pip install --upgrade sweetify.
but how to install the package after this
