### ISSUE TITLE
it doesn't work 

### ISSUE THREAD

**Issue by FILali1** [Atrox/sweetify-django#12]
I installed in last version of django "3" and just did what documentation says but still doesn't work

**Comment by alforropy** [comment]
same problem, I found this error on the web console 

`Swal is not defined`

**Comment by Atrox** [comment]
The first thing under Installation:
```Note: This package does not provide the client-side files of SweetAlert. You have to provide them yourself.```

@alforropy did you install SweetAlert itself and included it in your view?
