### ISSUE TITLE
Confirm deletion

### ISSUE THREAD

**Issue by maritogaleano** [Atrox/sweetify-django#15]
Is there a way to simulate this functionality ?:

`Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.value) {
	// Django code
    Swal.fire(
      'Deleted!',
      'Your file has been deleted.',
      'success'
    )
  }
})`

**Comment by Atrox** [comment]
See #9. There is currently no built-in way to react to clicks on the Sweetalert buttons.
