### ISSUE TITLE
No modal displayed

### ISSUE THREAD

**Issue by radaniba** [Atrox/sweetify-django#19]
Hi there,
I followed the exact same steps described here, and I loaded the CDN for sweetalert2 as well, that said, the call to the library seems to function but nothing shows up on the front end, no  modal displayed, no message and the page redirects successfully after the call.

Tried to put it on a Try/Catch thinking there might be some silent exception but nothing, the code is clean, but the alert is not working

Any ideas ?

**Comment by Atrox** [comment]
Hey @radaniba, are there any errors in the browser console?
