### ISSUE TITLE
How do I style the alert?

### ISSUE THREAD

**Issue by Moon-developer** [Atrox/sweetify-django#22]
I don't see an option to pass "className" to the alert for buttons or any other part. Is there a way around this by any chance?

**Comment by Atrox** [comment]
You can just pass normal sweetalert/sweetalert2 parameters. So if you wanted to change the color of the confirmButton in sweetalert2 you could simply pass the `confirmButtonColor` parameter.

Example:
```
sweetify.success(self.request, 'Test', confirmButtonColor='#3085d6')
```

**Comment by Atrox** [comment]
You're welcome :) It is documented in the README although not very obvious
```
You also can use any other available option that SweetAlert accepts:
```
